version: '3.3'
services:
  backend:
    env_file:
      - ./.env
    build: .
    ports:
      - 8000:8000
    restart: always
#     depends_on:
#       - db
#   db:
#     image: postgres:14-alpine
#     restart: always
#     ports:
#       - 5433:5432
#     environment:
#       - POSTGRES_DB=locker
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=admin

# volumes:
#   postgres_data: