# Generated by Django 4.2.5 on 2023-10-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlkr',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
