# Generated by Django 4.2.5 on 2023-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0002_bizlkr_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebook',
            name='payment_boo',
        ),
        migrations.AddField(
            model_name='prebook',
            name='payment_status',
            field=models.CharField(blank=True, db_comment='Payment Completed or not, initial value will be set to N, once payment is comepleted, this will be updated to Y', max_length=1, null=True),
        ),
    ]
