# Generated by Django 4.2.5 on 2023-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0003_remove_prebook_payment_boo_prebook_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='loc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
