# Generated by Django 4.2.6 on 2023-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0004_businessinfo_loc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='loc_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
