# Generated by Django 4.2.6 on 2023-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0005_businessinfo_loc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='biz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
