# Generated by Django 4.2.6 on 2023-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0006_alter_employee_biz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypin',
            name='sec_pin_pin',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
