# Generated by Django 4.2.6 on 2023-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0007_alter_securitypin_sec_pin_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypin',
            name='attempt',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
