# Generated by Django 4.2.6 on 2023-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0008_securitypin_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypin',
            name='attempt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
