# Generated by Django 4.2.6 on 2023-11-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0010_alter_securitypin_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='iot_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IotRequest',
            fields=[
                ('iot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('req_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=3, null=True)),
                ('request_json', models.JSONField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('request_dt', models.DateField(auto_now_add=True, null=True)),
                ('response_dt', models.DateField(auto_now_add=True, null=True)),
                ('biz', models.ForeignKey(db_column='biz_id', on_delete=django.db.models.deletion.DO_NOTHING, to='storage_locker.businessinfo')),
            ],
            options={
                'db_table': 'iot_request',
            },
        ),
    ]
