# Generated by Django 4.2.6 on 2023-11-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0011_businessinfo_iot_client_id_iotrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('remarks_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=3, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('response_dt', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'remarks',
            },
        ),
        migrations.AddField(
            model_name='iotrequest',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iotrequest',
            name='iot_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
