# Generated by Django 4.2.6 on 2023-11-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0012_remarks_iotrequest_status_alter_iotrequest_iot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotrequest',
            name='remarks',
            field=models.ForeignKey(db_column='remarks_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='storage_locker.remarks'),
            preserve_default=False,
        ),
    ]
