# Generated by Django 4.2.6 on 2023-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0013_iotrequest_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotrequest',
            name='remarks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
