# Generated by Django 4.2.6 on 2023-12-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0015_alter_businessinfo_iot_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotrequest',
            name='request_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotrequest',
            name='response_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('lock_no', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.DateField(blank=True, null=True)),
                ('initial_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage_locker.customer')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
