# Generated by Django 4.2.6 on 2023-12-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0016_alter_iotrequest_request_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlkrtype',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
