# Generated by Django 4.2.6 on 2023-12-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0017_bizlkrtype_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlkrtype',
            name='max_24_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
