# Generated by Django 4.2.6 on 2023-12-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0018_bizlkrtype_max_24_hrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
