# Generated by Django 4.2.6 on 2023-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0019_rename_customer_id_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
