# Generated by Django 4.2.6 on 2023-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0020_alter_invoice_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booked_durations',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
