# Generated by Django 4.2.6 on 2023-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0022_remove_book_booked_durations_book_booked_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('loc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
