# Generated by Django 4.2.6 on 2023-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0023_bizlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlocation',
            name='biz_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bizlocation',
            name='location_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
