# Generated by Django 4.2.6 on 2023-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0024_bizlocation_biz_id_alter_bizlocation_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkrsummary',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
