# Generated by Django 4.2.6 on 2023-12-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0025_lkrsummary_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlkr',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bizlkrtype',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebook',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
