# Generated by Django 4.2.6 on 2023-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0026_bizlkr_location_id_bizlkrtype_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizlkr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
