# Generated by Django 4.2.6 on 2023-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0029_activity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='usertype',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
