# Generated by Django 4.2.6 on 2023-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0030_employee_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
