# Generated by Django 4.2.6 on 2024-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0031_employee_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bizlkrtype',
            old_name='amt_per_hr',
            new_name='amt_per_unit',
        ),
        migrations.RenameField(
            model_name='bizlkrtype',
            old_name='max_24_hrs',
            new_name='max_24_amt',
        ),
        migrations.AddField(
            model_name='bizlkrtype',
            name='increment_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bizlkrtype',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
