# Generated by Django 4.2.6 on 2024-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0032_rename_amt_per_hr_bizlkrtype_amt_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizlkrtype',
            name='units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
