# Generated by Django 4.2.6 on 2024-01-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0033_alter_bizlkrtype_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlkrtype',
            name='max_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
