# Generated by Django 4.2.9 on 2024-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0034_bizlkrtype_max_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebook',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
