# Generated by Django 4.2.9 on 2024-01-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0036_prebook_plink_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
