# Generated by Django 4.2.9 on 2024-01-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0037_alter_paymenttype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='payment',
            name='book',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
