# Generated by Django 4.2.9 on 2024-01-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0038_remove_payment_payment_type_alter_payment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bank_name',
            new_name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_txn_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='txn_id',
        ),
    ]
