# Generated by Django 4.2.9 on 2024-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0039_rename_book_payment_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
