# Generated by Django 4.2.9 on 2024-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0040_alter_invoice_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebook',
            name='booking_hrs',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
