# Generated by Django 4.2.9 on 2024-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0041_alter_prebook_booking_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booked_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
