# Generated by Django 4.2.9 on 2024-01-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0043_payment_payment_gateway_payment_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reason',
            new_name='intent',
        ),
    ]
