# Generated by Django 4.2.9 on 2024-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0045_payment_biz_id_payment_loc_id_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_ref_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
