# Generated by Django 4.2.9 on 2024-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0046_book_book_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extended_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
