# Generated by Django 4.2.9 on 2024-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0048_remove_book_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='duration',
            field=models.DurationField(blank=True, db_comment='Calcualted when end dt is populated \n', null=True),
        ),
    ]
