# Generated by Django 4.2.9 on 2024-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0049_book_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=120, null=True)),
                ('pbook', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, db_comment='false(0) alive, true(1) expired', default=0, null=True)),
            ],
            options={
                'db_table': 'book_token',
            },
        ),
    ]
