# Generated by Django 4.2.9 on 2024-02-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0050_booktoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktoken',
            name='token',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
