# Generated by Django 4.2.9 on 2024-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0051_alter_booktoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('biz_id', models.IntegerField()),
                ('loc_id', models.IntegerField()),
                ('cu_id', models.CharField(max_length=3)),
                ('status', models.CharField(default=None, max_length=100, null=True)),
                ('locker_no', models.IntegerField(default=None, null=True)),
                ('lock_status', models.CharField(default=None, help_text='O(Open) or C(Close)', max_length=1, null=True)),
                ('ir_status', models.CharField(default=None, max_length=45, null=True)),
                ('added_dt', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'change_log',
            },
        ),
        migrations.CreateModel(
            name='CuCmd',
            fields=[
                ('cu_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('biz_id', models.IntegerField()),
                ('loc_id', models.IntegerField()),
                ('status_cmd', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'cucmd',
            },
        ),
        migrations.CreateModel(
            name='LockCmd',
            fields=[
                ('lock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('biz_id', models.IntegerField()),
                ('loc_id', models.IntegerField()),
                ('cu_id', models.CharField(max_length=3)),
                ('cu_lock_no', models.CharField(max_length=2)),
                ('lock_no', models.CharField(max_length=3)),
                ('open_cmd', models.CharField(max_length=20)),
                ('status_cmd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lock_cmd',
            },
        ),
        migrations.CreateModel(
            name='LockerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('biz_id', models.IntegerField(default=None, null=True)),
                ('loc_id', models.IntegerField(default=None, null=True)),
                ('locker_id', models.IntegerField(default=None, null=True)),
                ('lock_status', models.CharField(default=None, max_length=1, null=True)),
                ('ir_status', models.CharField(default=None, max_length=1, null=True)),
                ('added_dt', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'locker_status',
            },
        ),
        migrations.CreateModel(
            name='RouterInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('biz_id', models.IntegerField(default=None, null=True)),
                ('loc_id', models.IntegerField(default=None, null=True)),
                ('device_id', models.CharField(default=None, max_length=10, null=True)),
                ('ip_range_start', models.CharField(default=None, max_length=15, null=True)),
                ('ip_range_end', models.CharField(default=None, max_length=15, null=True)),
            ],
            options={
                'db_table': 'router_info',
            },
        ),
        migrations.CreateModel(
            name='RouterStatus',
            fields=[
                ('seq_no', models.IntegerField(primary_key=True, serialize=False)),
                ('biz_loc_id', models.CharField(default=None, max_length=10, null=True)),
                ('router_ip', models.CharField(default=None, max_length=15, null=True)),
                ('router_st', models.SmallIntegerField(default=None, null=True)),
                ('added_dt', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'router_status',
            },
        ),
    ]
