# Generated by Django 4.2.9 on 2024-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0053_alter_cucmd_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(blank=True, db_comment='Either Opened or Booked or Paid or Released', max_length=20, null=True),
        ),
    ]
