# Generated by Django 4.2.9 on 2024-02-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0054_alter_activity_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerstatus',
            name='seq_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
