# Generated by Django 4.2.9 on 2024-02-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0055_alter_routerstatus_seq_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cucmd',
            unique_together={('cu_id', 'biz_id', 'loc_id')},
        ),
    ]
