# Generated by Django 4.2.9 on 2024-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0056_alter_cucmd_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cucmd',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cucmd',
            constraint=models.UniqueConstraint(fields=('cu_id', 'biz_id', 'loc_id'), name='cu_cmd_pk'),
        ),
    ]
