# Generated by Django 4.2.9 on 2024-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0057_alter_cucmd_unique_together_cucmd_cu_cmd_pk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuCmd',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='initiated_by',
        ),
        migrations.AddField(
            model_name='activity',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebook',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
