# Generated by Django 4.2.9 on 2024-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0058_delete_cucmd_remove_activity_initiated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_id', models.CharField(max_length=3)),
                ('biz_id', models.IntegerField()),
                ('loc_id', models.IntegerField()),
                ('status_cmd', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'cu_cmd',
            },
        ),
        migrations.AddConstraint(
            model_name='cucmd',
            constraint=models.UniqueConstraint(fields=('cu_id', 'biz_id', 'loc_id'), name='cu_cmd_pk'),
        ),
    ]
