# Generated by Django 4.2.9 on 2024-02-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0060_remove_activity_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='loc_id',
        ),
    ]
