# Generated by Django 4.2.9 on 2024-02-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0061_remove_activity_loc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='biz_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='cus_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='loc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity_log',
        ),
    ]
