# Generated by Django 4.2.9 on 2024-02-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0065_payment_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlocation',
            name='biz_info',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='storage_locker.businessinfo'),
            preserve_default=False,
        ),
    ]
