# Generated by Django 4.2.9 on 2024-02-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_locker', '0066_bizlocation_biz_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
